
# 自动解析 Lofter 链接
autoParse: true

# 是否发送原图（可能会增加流量消耗）
sendOriginal: false

# 消息发送方式
# forward: 合并转发（默认）
# normal: 逐条发送
sendMode: forward

# 在解析到有图片时，单独发送第一张图片到聊天（常用于开启合并转发时预览）
sendFirstImage: false

# 合并转发外显消息（标题）
forwardTitle: 'Lofter解析结果'

# 合并转发内部QQ名（昵称），为空时使用默认Bot名称
forwardNickname: ''

# 超时时间（秒）
timeout: 30

# 是否显示标签
showTags: true

# 开启图片大小限制
enableImageSizeLimit: true

# 图片大小限制（MB）
imageSizeLimit: 8
